version: '3'

services:
  dtools:
    image: bplein/bpxtools:latest
    container_name: bpxtools
    hostname: bpxtools
    restart: always
    network_mode: "host"
    volumes:
      - $HOME/source:/root/source
      - $HOME/Downloads:/root/Downloads
      - $HOME/.kube:/root/.kube
      - $HOME/.kube:/root/.aws
      - $HOME/.ssh:/root/.ssh
      - $HOME/.px-deploy:/root/.px-deploy
